# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addFilm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddFilm(object):
    def setupUi(self, AddFilm):
        AddFilm.setObjectName("AddFilm")
        AddFilm.resize(413, 653)
        self.frame_3 = QtWidgets.QFrame(AddFilm)
        self.frame_3.setGeometry(QtCore.QRect(10, 10, 391, 631))
        self.frame_3.setStyleSheet("background-color: rgb(59, 59, 88);\n"
"border-radius:10px;\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setGeometry(QtCore.QRect(30, 30, 351, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(27)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0.460227, x2:1, y2:0.46, stop:0 rgba(231, 126, 186, 255), stop:1 rgba(170, 85, 255, 255));")
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.exit = QtWidgets.QPushButton(self.frame_3)
        self.exit.setGeometry(QtCore.QRect(350, 10, 22, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.exit.setFont(font)
        self.exit.setStyleSheet("QPushButton#exit{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.460227, x2:1, y2:0.46, stop:0 rgba(231, 126, 186, 255), stop:1 rgba(170, 85, 255, 255));\n"
"border-radius:10px;\n"
"font: 10pt \"Segoe UI\";\n"
"color:rgb(200, 200, 200);\n"
"}\n"
"QPushButton#exit:hover {\n"
"    font:  75 12pt \"Segoe UI\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#exit:pressed{\n"
"    \n"
"    color: rgb(59, 59, 88);\n"
"}")
        self.exit.setObjectName("exit")
        self.frame_9 = QtWidgets.QFrame(self.frame_3)
        self.frame_9.setGeometry(QtCore.QRect(30, 110, 331, 471))
        self.frame_9.setStyleSheet("background-color: rgb(39, 39, 60);")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.frame_2 = QtWidgets.QFrame(self.frame_9)
        self.frame_2.setGeometry(QtCore.QRect(30, 68, 274, 2))
        self.frame_2.setStyleSheet("background-color: rgb(100, 100, 150);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.title = QtWidgets.QLineEdit(self.frame_9)
        self.title.setGeometry(QtCore.QRect(30, 30, 274, 31))
        self.title.setStyleSheet("font: 15pt \"Segoe UI\";\n"
"color:rgb(200, 200, 200);")
        self.title.setObjectName("title")
        self.release = QtWidgets.QLineEdit(self.frame_9)
        self.release.setGeometry(QtCore.QRect(30, 82, 274, 31))
        self.release.setStyleSheet("font: 15pt \"Segoe UI\";\n"
"color:rgb(200, 200, 200);")
        self.release.setObjectName("release")
        self.frame_4 = QtWidgets.QFrame(self.frame_9)
        self.frame_4.setGeometry(QtCore.QRect(30, 120, 274, 2))
        self.frame_4.setStyleSheet("background-color: rgb(100, 100, 150);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.genre = QtWidgets.QLineEdit(self.frame_9)
        self.genre.setGeometry(QtCore.QRect(30, 132, 274, 31))
        self.genre.setStyleSheet("font: 15pt \"Segoe UI\";\n"
"color:rgb(200, 200, 200);")
        self.genre.setObjectName("genre")
        self.frame_5 = QtWidgets.QFrame(self.frame_9)
        self.frame_5.setGeometry(QtCore.QRect(30, 170, 274, 2))
        self.frame_5.setStyleSheet("background-color: rgb(100, 100, 150);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.age = QtWidgets.QComboBox(self.frame_9)
        self.age.setGeometry(QtCore.QRect(96, 185, 211, 31))
        self.age.setStyleSheet("font: 15pt \"Segoe UI\";\n"
"color:rgb(200, 200, 200);")
        self.age.setObjectName("age")
        self.age.addItem("")
        self.age.addItem("")
        self.age.addItem("")
        self.age.addItem("")
        self.age.addItem("")
        self.frame_6 = QtWidgets.QFrame(self.frame_9)
        self.frame_6.setGeometry(QtCore.QRect(30, 220, 274, 2))
        self.frame_6.setStyleSheet("background-color: rgb(100, 100, 150);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.duration = QtWidgets.QLineEdit(self.frame_9)
        self.duration.setGeometry(QtCore.QRect(30, 232, 274, 31))
        self.duration.setStyleSheet("font: 15pt \"Segoe UI\";\n"
"color:rgb(200, 200, 200);")
        self.duration.setFrame(True)
        self.duration.setObjectName("duration")
        self.frame_7 = QtWidgets.QFrame(self.frame_9)
        self.frame_7.setGeometry(QtCore.QRect(30, 270, 274, 2))
        self.frame_7.setStyleSheet("background-color: rgb(100, 100, 150);")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.seriesName = QtWidgets.QLineEdit(self.frame_9)
        self.seriesName.setGeometry(QtCore.QRect(30, 282, 274, 31))
        self.seriesName.setStyleSheet("font: 15pt \"Segoe UI\";\n"
"color:rgb(200, 200, 200);")
        self.seriesName.setText("")
        self.seriesName.setObjectName("seriesName")
        self.frame_8 = QtWidgets.QFrame(self.frame_9)
        self.frame_8.setGeometry(QtCore.QRect(30, 320, 274, 2))
        self.frame_8.setStyleSheet("background-color: rgb(100, 100, 150);")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.episode = QtWidgets.QLineEdit(self.frame_9)
        self.episode.setGeometry(QtCore.QRect(30, 330, 274, 31))
        self.episode.setStyleSheet("font: 15pt \"Segoe UI\";\n"
"color:rgb(200, 200, 200);")
        self.episode.setText("")
        self.episode.setObjectName("episode")
        self.frame_10 = QtWidgets.QFrame(self.frame_9)
        self.frame_10.setGeometry(QtCore.QRect(30, 368, 274, 2))
        self.frame_10.setStyleSheet("background-color: rgb(100, 100, 150);")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.label = QtWidgets.QLabel(self.frame_9)
        self.label.setGeometry(QtCore.QRect(35, 185, 61, 31))
        self.label.setStyleSheet("font: 15pt \"Segoe UI\";\n"
"color: rgb(119, 119, 130);")
        self.label.setObjectName("label")
        self.frame_11 = QtWidgets.QFrame(self.frame_9)
        self.frame_11.setGeometry(QtCore.QRect(30, 418, 274, 2))
        self.frame_11.setStyleSheet("background-color: rgb(100, 100, 150);")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.season = QtWidgets.QLineEdit(self.frame_9)
        self.season.setGeometry(QtCore.QRect(30, 380, 274, 31))
        self.season.setStyleSheet("font: 15pt \"Segoe UI\";\n"
"color:rgb(200, 200, 200);")
        self.season.setText("")
        self.season.setObjectName("season")
        self.label_3 = QtWidgets.QLabel(self.frame_9)
        self.label_3.setGeometry(QtCore.QRect(10, 450, 274, 16))
        self.label_3.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: rgb(119, 119, 130);")
        self.label_3.setObjectName("label_3")
        self.addButton = QtWidgets.QPushButton(self.frame_3)
        self.addButton.setGeometry(QtCore.QRect(30, 590, 331, 23))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.addButton.setFont(font)
        self.addButton.setStyleSheet("QPushButton#addButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.460227, x2:1, y2:0.46, stop:0 rgba(231, 126, 186, 255), stop:1 rgba(170, 85, 255, 255));\n"
"border-radius:10px;\n"
"font: 10pt \"Segoe UI\";\n"
"color:rgb(200, 200, 200);\n"
"}\n"
"QPushButton#addButton:hover {\n"
"    font:  75 12pt \"Segoe UI\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#addButton:pressed{\n"
"    \n"
"    color: rgb(59, 59, 88);\n"
"}")
        self.addButton.setObjectName("addButton")

        self.retranslateUi(AddFilm)
        QtCore.QMetaObject.connectSlotsByName(AddFilm)

    def retranslateUi(self, AddFilm):
        _translate = QtCore.QCoreApplication.translate
        AddFilm.setWindowTitle(_translate("AddFilm", "Form"))
        self.label_2.setText(_translate("AddFilm", "Film hinzufügen"))
        self.exit.setText(_translate("AddFilm", "X"))
        self.title.setPlaceholderText(_translate("AddFilm", "Title"))
        self.release.setPlaceholderText(_translate("AddFilm", "Jahr"))
        self.genre.setPlaceholderText(_translate("AddFilm", "Genre"))
        self.age.setCurrentText(_translate("AddFilm", "0"))
        self.age.setItemText(0, _translate("AddFilm", "0"))
        self.age.setItemText(1, _translate("AddFilm", "6"))
        self.age.setItemText(2, _translate("AddFilm", "12"))
        self.age.setItemText(3, _translate("AddFilm", "16"))
        self.age.setItemText(4, _translate("AddFilm", "18"))
        self.duration.setPlaceholderText(_translate("AddFilm", "Länge in Minuten"))
        self.seriesName.setPlaceholderText(_translate("AddFilm", "Serien-Name"))
        self.episode.setPlaceholderText(_translate("AddFilm", "Episode*"))
        self.label.setText(_translate("AddFilm", "Alter:"))
        self.season.setPlaceholderText(_translate("AddFilm", "Staffel*"))
        self.label_3.setText(_translate("AddFilm", "* nur für Serien"))
        self.addButton.setText(_translate("AddFilm", "Hinzufügen"))
