# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addPerson.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(397, 432)
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 391, 421))
        self.frame_3.setStyleSheet("background-color: rgb(59, 59, 88);\n"
"border-radius:10px;\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setGeometry(QtCore.QRect(30, 30, 351, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(27)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0.460227, x2:1, y2:0.46, stop:0 rgba(231, 126, 186, 255), stop:1 rgba(170, 85, 255, 255));")
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.exit = QtWidgets.QPushButton(self.frame_3)
        self.exit.setGeometry(QtCore.QRect(350, 10, 22, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.exit.setFont(font)
        self.exit.setStyleSheet("QPushButton#exit{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.460227, x2:1, y2:0.46, stop:0 rgba(231, 126, 186, 255), stop:1 rgba(170, 85, 255, 255));\n"
"border-radius:10px;\n"
"font: 10pt \"Segoe UI\";\n"
"color:rgb(200, 200, 200);\n"
"}\n"
"QPushButton#exit:hover {\n"
"    font:  75 12pt \"Segoe UI\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#exit:pressed{\n"
"    \n"
"    color: rgb(59, 59, 88);\n"
"}")
        self.exit.setObjectName("exit")
        self.frame_9 = QtWidgets.QFrame(self.frame_3)
        self.frame_9.setGeometry(QtCore.QRect(30, 110, 331, 261))
        self.frame_9.setStyleSheet("background-color: rgb(39, 39, 60);")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.frame_2 = QtWidgets.QFrame(self.frame_9)
        self.frame_2.setGeometry(QtCore.QRect(30, 68, 274, 2))
        self.frame_2.setStyleSheet("background-color: rgb(100, 100, 150);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.forname = QtWidgets.QLineEdit(self.frame_9)
        self.forname.setGeometry(QtCore.QRect(30, 30, 274, 31))
        self.forname.setStyleSheet("font: 15pt \"Segoe UI\";\n"
"color:rgb(200, 200, 200);")
        self.forname.setObjectName("forname")
        self.surname = QtWidgets.QLineEdit(self.frame_9)
        self.surname.setGeometry(QtCore.QRect(30, 82, 274, 31))
        self.surname.setStyleSheet("font: 15pt \"Segoe UI\";\n"
"color:rgb(200, 200, 200);")
        self.surname.setObjectName("surname")
        self.frame_4 = QtWidgets.QFrame(self.frame_9)
        self.frame_4.setGeometry(QtCore.QRect(30, 120, 274, 2))
        self.frame_4.setStyleSheet("background-color: rgb(100, 100, 150);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.dateOfBirth = QtWidgets.QLineEdit(self.frame_9)
        self.dateOfBirth.setGeometry(QtCore.QRect(30, 132, 274, 31))
        self.dateOfBirth.setStyleSheet("font: 15pt \"Segoe UI\";\n"
"color:rgb(200, 200, 200);")
        self.dateOfBirth.setObjectName("dateOfBirth")
        self.frame_5 = QtWidgets.QFrame(self.frame_9)
        self.frame_5.setGeometry(QtCore.QRect(30, 170, 274, 2))
        self.frame_5.setStyleSheet("background-color: rgb(100, 100, 150);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.sex = QtWidgets.QComboBox(self.frame_9)
        self.sex.setGeometry(QtCore.QRect(146, 185, 161, 31))
        self.sex.setStyleSheet("font: 15pt \"Segoe UI\";\n"
"color:rgb(200, 200, 200);")
        self.sex.setObjectName("sex")
        self.sex.addItem("")
        self.sex.addItem("")
        self.sex.addItem("")
        self.frame_6 = QtWidgets.QFrame(self.frame_9)
        self.frame_6.setGeometry(QtCore.QRect(30, 220, 274, 2))
        self.frame_6.setStyleSheet("background-color: rgb(100, 100, 150);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label = QtWidgets.QLabel(self.frame_9)
        self.label.setGeometry(QtCore.QRect(35, 185, 111, 31))
        self.label.setStyleSheet("font: 15pt \"Segoe UI\";\n"
"color: rgb(119, 119, 130);")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.frame_9)
        self.label_3.setGeometry(QtCore.QRect(30, 240, 291, 21))
        self.label_3.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: rgb(119, 119, 130);")
        self.label_3.setObjectName("label_3")
        self.addButton = QtWidgets.QPushButton(self.frame_3)
        self.addButton.setGeometry(QtCore.QRect(30, 380, 331, 23))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.addButton.setFont(font)
        self.addButton.setStyleSheet("QPushButton#addButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.460227, x2:1, y2:0.46, stop:0 rgba(231, 126, 186, 255), stop:1 rgba(170, 85, 255, 255));\n"
"border-radius:10px;\n"
"font: 10pt \"Segoe UI\";\n"
"color:rgb(200, 200, 200);\n"
"}\n"
"QPushButton#addButton:hover {\n"
"    font:  75 12pt \"Segoe UI\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#addButton:pressed{\n"
"    \n"
"    color: rgb(59, 59, 88);\n"
"}")
        self.addButton.setObjectName("addButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Person hinzufügen"))
        self.exit.setText(_translate("Form", "X"))
        self.forname.setPlaceholderText(_translate("Form", "Vorname"))
        self.surname.setPlaceholderText(_translate("Form", "Nachname"))
        self.dateOfBirth.setPlaceholderText(_translate("Form", "Geburtstag"))
        self.sex.setCurrentText(_translate("Form", "m"))
        self.sex.setItemText(0, _translate("Form", "m"))
        self.sex.setItemText(1, _translate("Form", "w"))
        self.sex.setItemText(2, _translate("Form", "d"))
        self.label.setText(_translate("Form", "Geschlecht:"))
        self.label_3.setText(_translate("Form", "Alle Felder müssen valide ausgefüllt sein"))
        self.addButton.setText(_translate("Form", "Hinzufügen"))
