# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'changeFilm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(695, 770)
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 691, 761))
        self.frame_3.setStyleSheet("background-color: rgb(59, 59, 88);\n"
"border-radius:10px;\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setGeometry(QtCore.QRect(30, 30, 351, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(27)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0.460227, x2:1, y2:0.46, stop:0 rgba(231, 126, 186, 255), stop:1 rgba(170, 85, 255, 255));")
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.frame_17 = QtWidgets.QFrame(self.frame_3)
        self.frame_17.setGeometry(QtCore.QRect(30, 110, 631, 591))
        self.frame_17.setStyleSheet("background-color: rgb(39, 39, 60);")
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.frame_18 = QtWidgets.QFrame(self.frame_17)
        self.frame_18.setGeometry(QtCore.QRect(30, 68, 274, 2))
        self.frame_18.setStyleSheet("background-color: rgb(100, 100, 150);")
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.frame_26 = QtWidgets.QFrame(self.frame_18)
        self.frame_26.setGeometry(QtCore.QRect(0, 0, 274, 2))
        self.frame_26.setStyleSheet("background-color: rgb(100, 100, 150);")
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.title = QtWidgets.QLineEdit(self.frame_17)
        self.title.setEnabled(False)
        self.title.setGeometry(QtCore.QRect(30, 30, 274, 31))
        self.title.setStyleSheet("font: 15pt \"Segoe UI\";\n"
"color:rgb(200, 200, 200);")
        self.title.setText("")
        self.title.setObjectName("title")
        self.release = QtWidgets.QLineEdit(self.frame_17)
        self.release.setEnabled(False)
        self.release.setGeometry(QtCore.QRect(30, 82, 274, 31))
        self.release.setStyleSheet("font: 15pt \"Segoe UI\";\n"
"color:rgb(200, 200, 200);")
        self.release.setObjectName("release")
        self.frame_19 = QtWidgets.QFrame(self.frame_17)
        self.frame_19.setGeometry(QtCore.QRect(30, 120, 274, 2))
        self.frame_19.setStyleSheet("background-color: rgb(100, 100, 150);")
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.genre = QtWidgets.QLineEdit(self.frame_17)
        self.genre.setEnabled(False)
        self.genre.setGeometry(QtCore.QRect(30, 132, 274, 31))
        self.genre.setStyleSheet("font: 15pt \"Segoe UI\";\n"
"color:rgb(200, 200, 200);")
        self.genre.setObjectName("genre")
        self.frame_20 = QtWidgets.QFrame(self.frame_17)
        self.frame_20.setGeometry(QtCore.QRect(30, 170, 274, 2))
        self.frame_20.setStyleSheet("background-color: rgb(100, 100, 150);")
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.age = QtWidgets.QComboBox(self.frame_17)
        self.age.setEnabled(False)
        self.age.setGeometry(QtCore.QRect(96, 185, 211, 31))
        self.age.setStyleSheet("font: 15pt \"Segoe UI\";\n"
"color:rgb(200, 200, 200);")
        self.age.setObjectName("age")
        self.age.addItem("")
        self.age.addItem("")
        self.age.addItem("")
        self.age.addItem("")
        self.age.addItem("")
        self.frame_21 = QtWidgets.QFrame(self.frame_17)
        self.frame_21.setGeometry(QtCore.QRect(30, 220, 274, 2))
        self.frame_21.setStyleSheet("background-color: rgb(100, 100, 150);")
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.duration = QtWidgets.QLineEdit(self.frame_17)
        self.duration.setEnabled(False)
        self.duration.setGeometry(QtCore.QRect(30, 232, 274, 31))
        self.duration.setStyleSheet("font: 15pt \"Segoe UI\";\n"
"color:rgb(200, 200, 200);")
        self.duration.setFrame(True)
        self.duration.setObjectName("duration")
        self.frame_22 = QtWidgets.QFrame(self.frame_17)
        self.frame_22.setGeometry(QtCore.QRect(30, 270, 274, 2))
        self.frame_22.setStyleSheet("background-color: rgb(100, 100, 150);")
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.seriesName = QtWidgets.QLineEdit(self.frame_17)
        self.seriesName.setEnabled(False)
        self.seriesName.setGeometry(QtCore.QRect(30, 282, 274, 31))
        self.seriesName.setStyleSheet("font: 15pt \"Segoe UI\";\n"
"color:rgb(200, 200, 200);")
        self.seriesName.setText("")
        self.seriesName.setObjectName("seriesName")
        self.frame_23 = QtWidgets.QFrame(self.frame_17)
        self.frame_23.setGeometry(QtCore.QRect(30, 320, 274, 2))
        self.frame_23.setStyleSheet("background-color: rgb(100, 100, 150);")
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.episode = QtWidgets.QLineEdit(self.frame_17)
        self.episode.setEnabled(False)
        self.episode.setGeometry(QtCore.QRect(30, 330, 274, 31))
        self.episode.setStyleSheet("font: 15pt \"Segoe UI\";\n"
"color:rgb(200, 200, 200);")
        self.episode.setText("")
        self.episode.setObjectName("episode")
        self.frame_24 = QtWidgets.QFrame(self.frame_17)
        self.frame_24.setGeometry(QtCore.QRect(30, 368, 274, 2))
        self.frame_24.setStyleSheet("background-color: rgb(100, 100, 150);")
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.label_7 = QtWidgets.QLabel(self.frame_17)
        self.label_7.setGeometry(QtCore.QRect(35, 185, 61, 31))
        self.label_7.setStyleSheet("font: 15pt \"Segoe UI\";\n"
"color: rgb(119, 119, 130);")
        self.label_7.setObjectName("label_7")
        self.frame_25 = QtWidgets.QFrame(self.frame_17)
        self.frame_25.setGeometry(QtCore.QRect(30, 418, 274, 2))
        self.frame_25.setStyleSheet("background-color: rgb(100, 100, 150);")
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.season = QtWidgets.QLineEdit(self.frame_17)
        self.season.setEnabled(False)
        self.season.setGeometry(QtCore.QRect(30, 380, 274, 31))
        self.season.setStyleSheet("font: 15pt \"Segoe UI\";\n"
"color:rgb(200, 200, 200);")
        self.season.setText("")
        self.season.setObjectName("season")
        self.label_9 = QtWidgets.QLabel(self.frame_17)
        self.label_9.setGeometry(QtCore.QRect(30, 430, 111, 31))
        self.label_9.setStyleSheet("font: 15pt \"Segoe UI\";\n"
"color: rgb(119, 119, 130);")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame_17)
        self.label_10.setGeometry(QtCore.QRect(270, 427, 31, 31))
        self.label_10.setStyleSheet("font: 15pt \"Segoe UI\";\n"
"color: rgb(119, 119, 130);")
        self.label_10.setObjectName("label_10")
        self.rate = QtWidgets.QComboBox(self.frame_17)
        self.rate.setEnabled(False)
        self.rate.setGeometry(QtCore.QRect(130, 430, 141, 31))
        self.rate.setStyleSheet("font: 15pt \"Segoe UI\";\n"
"color:rgb(200, 200, 200);")
        self.rate.setObjectName("rate")
        self.rate.addItem("")
        self.rate.setItemText(0, "")
        self.rate.addItem("")
        self.rate.addItem("")
        self.rate.addItem("")
        self.rate.addItem("")
        self.rate.addItem("")
        self.frame_27 = QtWidgets.QFrame(self.frame_17)
        self.frame_27.setGeometry(QtCore.QRect(30, 470, 274, 2))
        self.frame_27.setStyleSheet("background-color: rgb(100, 100, 150);")
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.frame_30 = QtWidgets.QFrame(self.frame_27)
        self.frame_30.setGeometry(QtCore.QRect(0, 0, 274, 2))
        self.frame_30.setStyleSheet("background-color: rgb(100, 100, 150);")
        self.frame_30.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.filmRelatedPersonsList = QtWidgets.QListWidget(self.frame_17)
        self.filmRelatedPersonsList.setGeometry(QtCore.QRect(325, 71, 281, 301))
        self.filmRelatedPersonsList.setStyleSheet("font: 15pt \"Segoe UI\";\n"
"color:rgb(200, 200, 200);\n"
"background-color: rgb(35, 35, 55);")
        self.filmRelatedPersonsList.setObjectName("filmRelatedPersonsList")
        self.forname = QtWidgets.QLineEdit(self.frame_17)
        self.forname.setEnabled(False)
        self.forname.setGeometry(QtCore.QRect(330, 390, 274, 31))
        self.forname.setStyleSheet("font: 15pt \"Segoe UI\";\n"
"color:rgb(200, 200, 200);QLineEdit[text=\"\"]{ color:gray; }")
        self.forname.setText("")
        self.forname.setObjectName("forname")
        self.frame_28 = QtWidgets.QFrame(self.frame_17)
        self.frame_28.setGeometry(QtCore.QRect(330, 420, 274, 2))
        self.frame_28.setStyleSheet("background-color: rgb(100, 100, 150);")
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.role = QtWidgets.QLineEdit(self.frame_17)
        self.role.setEnabled(False)
        self.role.setGeometry(QtCore.QRect(330, 490, 274, 31))
        self.role.setStyleSheet("font: 15pt \"Segoe UI\";\n"
"color:rgb(200, 200, 200);QLineEdit[text=\"\"]{ color:gray; }")
        self.role.setText("")
        self.role.setObjectName("role")
        self.frame_29 = QtWidgets.QFrame(self.frame_17)
        self.frame_29.setGeometry(QtCore.QRect(330, 520, 274, 2))
        self.frame_29.setStyleSheet("background-color: rgb(100, 100, 150);")
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.surname = QtWidgets.QLineEdit(self.frame_17)
        self.surname.setEnabled(False)
        self.surname.setGeometry(QtCore.QRect(330, 440, 274, 31))
        self.surname.setStyleSheet("font: 15pt \"Segoe UI\";\n"
"color:rgb(200, 200, 200);\n"
"QLineEdit[text=\\\"\\\"]{ color:gray; };")
        self.surname.setText("")
        self.surname.setObjectName("surname")
        self.frame_31 = QtWidgets.QFrame(self.frame_17)
        self.frame_31.setGeometry(QtCore.QRect(330, 470, 274, 2))
        self.frame_31.setStyleSheet("background-color: rgb(100, 100, 150);")
        self.frame_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_31.setObjectName("frame_31")
        self.label_2 = QtWidgets.QLabel(self.frame_17)
        self.label_2.setGeometry(QtCore.QRect(330, 30, 91, 31))
        self.label_2.setStyleSheet("font: 17pt \"Segoe UI\";\n"
"color:rgb(200, 200, 200);")
        self.label_2.setObjectName("label_2")
        self.resetButton = QtWidgets.QPushButton(self.frame_17)
        self.resetButton.setGeometry(QtCore.QRect(604, 395, 21, 23))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.resetButton.setFont(font)
        self.resetButton.setStyleSheet("QPushButton#resetButton{\n"
"font: 15pt \"Segoe UI\";\n"
"color: qlineargradient(spread:pad, x1:0, y1:0.460227, x2:1, y2:0.46, stop:0 rgba(231, 126, 186, 255), stop:1 rgba(170, 85, 255, 255));\n"
"}\n"
"QPushButton#resetButton:hover {\n"
"    font:  75 12pt \"Segoe UI\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#resetButton:pressed{\n"
"    \n"
"    color: rgb(59, 59, 88);\n"
"}")
        self.resetButton.setObjectName("resetButton")
        self.label_4 = QtWidgets.QLabel(self.frame_17)
        self.label_4.setGeometry(QtCore.QRect(330, 526, 561, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("font: 8pt \"Segoe UI\";\n"
"color: rgb(119, 119, 130);")
        self.label_4.setObjectName("label_4")
        self.changeButton = QtWidgets.QPushButton(self.frame_3)
        self.changeButton.setGeometry(QtCore.QRect(30, 720, 121, 23))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.changeButton.setFont(font)
        self.changeButton.setStyleSheet("QPushButton#changeButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.460227, x2:1, y2:0.46, stop:0 rgba(231, 126, 186, 255), stop:1 rgba(170, 85, 255, 255));\n"
"border-radius:10px;\n"
"font: 10pt \"Segoe UI\";\n"
"color:rgb(200, 200, 200);\n"
"}\n"
"QPushButton#changeButton:hover {\n"
"    font:  75 12pt \"Segoe UI\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#changeButton:pressed{\n"
"    \n"
"    color: rgb(59, 59, 88);\n"
"}")
        self.changeButton.setObjectName("changeButton")
        self.deleteButton = QtWidgets.QPushButton(self.frame_3)
        self.deleteButton.setGeometry(QtCore.QRect(540, 720, 121, 23))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.deleteButton.setFont(font)
        self.deleteButton.setStyleSheet("QPushButton#deleteButton{\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:1, x2:1, y2:0.307, stop:0.0909091 rgba(244, 108, 203, 255), stop:1 rgba(247, 127, 127, 255));\n"
"border-radius:10px;\n"
"font: 10pt \"Segoe UI\";\n"
"color:rgb(200, 200, 200);\n"
"}\n"
"QPushButton#deleteButton:hover {\n"
"    font:  75 12pt \"Segoe UI\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#deleteButton:pressed{\n"
"    \n"
"    color: rgb(59, 59, 88);\n"
"}")
        self.deleteButton.setObjectName("deleteButton")
        self.exit = QtWidgets.QPushButton(self.frame_3)
        self.exit.setGeometry(QtCore.QRect(660, 10, 22, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.exit.setFont(font)
        self.exit.setStyleSheet("QPushButton#exit{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.460227, x2:1, y2:0.46, stop:0 rgba(231, 126, 186, 255), stop:1 rgba(170, 85, 255, 255));\n"
"border-radius:10px;\n"
"font: 10pt \"Segoe UI\";\n"
"color:rgb(200, 200, 200);\n"
"}\n"
"QPushButton#exit:hover {\n"
"    font:  75 12pt \"Segoe UI\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#exit:pressed{\n"
"    \n"
"    color: rgb(59, 59, 88);\n"
"}")
        self.exit.setObjectName("exit")
        self.changePersonRoleButton = QtWidgets.QPushButton(self.frame_3)
        self.changePersonRoleButton.setEnabled(True)
        self.changePersonRoleButton.setGeometry(QtCore.QRect(360, 660, 131, 23))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.changePersonRoleButton.setFont(font)
        self.changePersonRoleButton.setStyleSheet("QPushButton#changePersonRoleButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.460227, x2:1, y2:0.46, stop:0 rgba(231, 126, 186, 255), stop:1 rgba(170, 85, 255, 255));\n"
"border-radius:10px;\n"
"font: 10pt \"Segoe UI\";\n"
"color:rgb(200, 200, 200);\n"
"}\n"
"QPushButton#changePersonRoleButton:hover {\n"
"    font:  75 12pt \"Segoe UI\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#changePersonRoleButton:pressed{\n"
"    \n"
"    color: rgb(59, 59, 88);\n"
"}")
        self.changePersonRoleButton.setObjectName("changePersonRoleButton")
        self.deleteFilmRelatedPerson = QtWidgets.QPushButton(self.frame_3)
        self.deleteFilmRelatedPerson.setEnabled(True)
        self.deleteFilmRelatedPerson.setGeometry(QtCore.QRect(510, 660, 121, 23))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.deleteFilmRelatedPerson.setFont(font)
        self.deleteFilmRelatedPerson.setStyleSheet("QPushButton#deleteFilmRelatedPerson{\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:1, x2:1, y2:0.307, stop:0.0909091 rgba(244, 108, 203, 255), stop:1 rgba(247, 127, 127, 255));\n"
"border-radius:10px;\n"
"font: 10pt \"Segoe UI\";\n"
"color:rgb(200, 200, 200);\n"
"}\n"
"QPushButton#deleteFilmRelatedPerson:hover {\n"
"    font:  75 12pt \"Segoe UI\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#deleteFilmRelatedPerson:pressed{\n"
"    \n"
"    color: rgb(59, 59, 88);\n"
"}")
        self.deleteFilmRelatedPerson.setObjectName("deleteFilmRelatedPerson")
        self.searchPersonButton = QtWidgets.QPushButton(self.frame_3)
        self.searchPersonButton.setEnabled(True)
        self.searchPersonButton.setGeometry(QtCore.QRect(360, 660, 271, 23))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.searchPersonButton.setFont(font)
        self.searchPersonButton.setStyleSheet("QPushButton#searchPersonButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.460227, x2:1, y2:0.46, stop:0 rgba(231, 126, 186, 255), stop:1 rgba(170, 85, 255, 255));\n"
"border-radius:10px;\n"
"font: 10pt \"Segoe UI\";\n"
"color:rgb(200, 200, 200);\n"
"}\n"
"QPushButton#searchPersonButton:hover {\n"
"    font:  75 12pt \"Segoe UI\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#searchPersonButton:pressed{\n"
"    \n"
"    color: rgb(59, 59, 88);\n"
"}")
        self.searchPersonButton.setObjectName("searchPersonButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<FILM>"))
        self.title.setPlaceholderText(_translate("Form", "Title"))
        self.release.setPlaceholderText(_translate("Form", "Jahr"))
        self.genre.setPlaceholderText(_translate("Form", "Genre"))
        self.age.setCurrentText(_translate("Form", "0"))
        self.age.setItemText(0, _translate("Form", "0"))
        self.age.setItemText(1, _translate("Form", "6"))
        self.age.setItemText(2, _translate("Form", "12"))
        self.age.setItemText(3, _translate("Form", "16"))
        self.age.setItemText(4, _translate("Form", "18"))
        self.duration.setPlaceholderText(_translate("Form", "Länge in Minuten"))
        self.seriesName.setPlaceholderText(_translate("Form", "Serien-Name"))
        self.episode.setPlaceholderText(_translate("Form", "Episode*"))
        self.label_7.setText(_translate("Form", "Alter:"))
        self.season.setPlaceholderText(_translate("Form", "Staffel*"))
        self.label_9.setText(_translate("Form", "Bewertung:"))
        self.label_10.setText(_translate("Form", "⭐"))
        self.rate.setItemText(1, _translate("Form", "1"))
        self.rate.setItemText(2, _translate("Form", "2"))
        self.rate.setItemText(3, _translate("Form", "3"))
        self.rate.setItemText(4, _translate("Form", "4"))
        self.rate.setItemText(5, _translate("Form", "5"))
        self.forname.setPlaceholderText(_translate("Form", "Person (Vorname)"))
        self.role.setPlaceholderText(_translate("Form", "Rolle"))
        self.surname.setPlaceholderText(_translate("Form", "Person (Nachname)"))
        self.label_2.setText(_translate("Form", "Rollen"))
        self.resetButton.setText(_translate("Form", "X"))
        self.label_4.setText(_translate("Form", "Rollen nur mit einem Komma trennen (Ohne Leerzeichen)"))
        self.changeButton.setText(_translate("Form", "Ändern"))
        self.deleteButton.setText(_translate("Form", "Löschen"))
        self.exit.setText(_translate("Form", "X"))
        self.changePersonRoleButton.setText(_translate("Form", "Ändern"))
        self.deleteFilmRelatedPerson.setText(_translate("Form", "Rollen löschen"))
        self.searchPersonButton.setText(_translate("Form", "Suchen"))
