# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'crewManager.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CrewManager(object):
    def setupUi(self, CrewManager):
        CrewManager.setObjectName("CrewManager")
        CrewManager.resize(896, 471)
        self.frame = QtWidgets.QFrame(CrewManager)
        self.frame.setGeometry(QtCore.QRect(10, 30, 861, 421))
        self.frame.setStyleSheet("background-color: rgb(59, 59, 88);\n"
"border-radius:10px;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(70, 25, 341, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(27)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label.setFont(font)
        self.label.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0.460227, x2:1, y2:0.46, stop:0 rgba(231, 126, 186, 255), stop:1 rgba(170, 85, 255, 255));")
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.exit = QtWidgets.QPushButton(self.frame)
        self.exit.setGeometry(QtCore.QRect(835, 5, 22, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.exit.setFont(font)
        self.exit.setStyleSheet("QPushButton#exit{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.460227, x2:1, y2:0.46, stop:0 rgba(231, 126, 186, 255), stop:1 rgba(170, 85, 255, 255));\n"
"border-radius:10px;\n"
"font: 10pt \"Segoe UI\";\n"
"color:rgb(200, 200, 200);\n"
"}\n"
"QPushButton#exit:hover {\n"
"    font:  75 12pt \"Segoe UI\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#exit:pressed{\n"
"    \n"
"    color: rgb(59, 59, 88);\n"
"}")
        self.exit.setObjectName("exit")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(70, 90, 771, 311))
        self.frame_3.setStyleSheet("background-color: rgb(39, 39, 60);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.crewList = QtWidgets.QListWidget(self.frame_3)
        self.crewList.setGeometry(QtCore.QRect(15, 11, 741, 291))
        self.crewList.setStyleSheet("font: 20pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);")
        self.crewList.setObjectName("crewList")
        self.backButton = QtWidgets.QPushButton(self.frame)
        self.backButton.setGeometry(QtCore.QRect(20, 30, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.backButton.setFont(font)
        self.backButton.setStyleSheet("QPushButton#backButton{\n"
"color: qlineargradient(spread:pad, x1:0, y1:0.460227, x2:1, y2:0.46, stop:0 rgba(231, 126, 186, 255), stop:1 rgba(170, 85, 255, 255));\n"
"font: 30pt \"Segoe UI\";\n"
"\n"
"}\n"
"QPushButton#backButton:hover {\n"
"    font:  75 25pt \"Segoe UI\";\n"
"}\n"
"\n"
"QPushButton#backButton:pressed{\n"
"    color: rgb(59, 59, 88);\n"
"}")
        self.backButton.setObjectName("backButton")
        self.addPersonButton = QtWidgets.QPushButton(self.frame)
        self.addPersonButton.setGeometry(QtCore.QRect(810, 49, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(25)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.addPersonButton.setFont(font)
        self.addPersonButton.setStyleSheet("QPushButton#addPersonButton{\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:1, x2:1, y2:0.307, stop:0.0909091 rgba(244, 108, 203, 255), stop:1 rgba(247, 127, 127, 255));\n"
"border-radius:15px;\n"
"font: 25pt \"Segoe UI\";\n"
"color:rgb(200, 200, 200);\n"
"\n"
"}\n"
"QPushButton#addPersonButton:hover {\n"
"    font:  75 22pt \"Segoe UI\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#addPersonButton:pressed{\n"
"    \n"
"    color: rgb(59, 59, 88);\n"
"}")
        self.addPersonButton.setObjectName("addPersonButton")

        self.retranslateUi(CrewManager)
        QtCore.QMetaObject.connectSlotsByName(CrewManager)

    def retranslateUi(self, CrewManager):
        _translate = QtCore.QCoreApplication.translate
        CrewManager.setWindowTitle(_translate("CrewManager", "Form"))
        self.label.setText(_translate("CrewManager", "Crew-Management"))
        self.exit.setText(_translate("CrewManager", "X"))
        self.backButton.setText(_translate("CrewManager", "<"))
        self.addPersonButton.setText(_translate("CrewManager", "+"))
