# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'filmManager.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1248, 588)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(80, 80, 1151, 431))
        self.frame.setStyleSheet("background-color: rgb(59, 59, 88);\n"
"border-radius:10px;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(60, 25, 351, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(27)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0.460227, x2:1, y2:0.46, stop:0 rgba(231, 126, 186, 255), stop:1 rgba(170, 85, 255, 255));")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(30, 90, 191, 121))
        self.frame_2.setStyleSheet("background-color: rgb(39, 39, 60);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.checkBox = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox.setGeometry(QtCore.QRect(20, 60, 92, 23))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox.setFont(font)
        self.checkBox.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox.setObjectName("checkBox")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.checkBox_2 = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_2.setGeometry(QtCore.QRect(20, 90, 92, 23))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox_2.setObjectName("checkBox_2")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setGeometry(QtCore.QRect(-10, 40, 220, 2))
        self.frame_4.setStyleSheet("background-color: rgb(100, 100, 150);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        self.frame_6.setGeometry(QtCore.QRect(0, 0, 191, 121))
        self.frame_6.setStyleSheet("background-color: rgb(39, 39, 60);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.checkBox_3 = QtWidgets.QCheckBox(self.frame_6)
        self.checkBox_3.setGeometry(QtCore.QRect(20, 60, 92, 23))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox_3.setObjectName("checkBox_3")
        self.label_3 = QtWidgets.QLabel(self.frame_6)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.frame_6)
        self.checkBox_4.setGeometry(QtCore.QRect(20, 90, 92, 23))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox_4.setObjectName("checkBox_4")
        self.frame_7 = QtWidgets.QFrame(self.frame_6)
        self.frame_7.setGeometry(QtCore.QRect(-10, 40, 220, 2))
        self.frame_7.setStyleSheet("background-color: rgb(100, 100, 150);")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.frame_8 = QtWidgets.QFrame(self.frame_6)
        self.frame_8.setGeometry(QtCore.QRect(50, 40, 2, 300))
        self.frame_8.setStyleSheet("background-color: rgb(100, 100, 150);")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.exit = QtWidgets.QPushButton(self.frame)
        self.exit.setGeometry(QtCore.QRect(1125, 5, 22, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.exit.setFont(font)
        self.exit.setStyleSheet("QPushButton#exit{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.460227, x2:1, y2:0.46, stop:0 rgba(231, 126, 186, 255), stop:1 rgba(170, 85, 255, 255));\n"
"border-radius:10px;\n"
"font: 10pt \"Segoe UI\";\n"
"color:rgb(200, 200, 200);\n"
"}\n"
"QPushButton#exit:hover {\n"
"    font:  75 12pt \"Segoe UI\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#exit:pressed{\n"
"    \n"
"    color: rgb(59, 59, 88);\n"
"}")
        self.exit.setObjectName("exit")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(240, 120, 891, 281))
        self.frame_3.setStyleSheet("background-color: rgb(39, 39, 60);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.videoList = QtWidgets.QListWidget(self.frame_3)
        self.videoList.setGeometry(QtCore.QRect(15, 20, 861, 271))
        self.videoList.setStyleSheet("font: 20pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);")
        self.videoList.setObjectName("videoList")
        self.backButton = QtWidgets.QPushButton(self.frame)
        self.backButton.setGeometry(QtCore.QRect(20, 30, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.backButton.setFont(font)
        self.backButton.setStyleSheet("QPushButton#backButton{\n"
"color: qlineargradient(spread:pad, x1:0, y1:0.460227, x2:1, y2:0.46, stop:0 rgba(231, 126, 186, 255), stop:1 rgba(170, 85, 255, 255));\n"
"font: 30pt \"Segoe UI\";\n"
"\n"
"}\n"
"QPushButton#backButton:hover {\n"
"    font:  75 25pt \"Segoe UI\";\n"
"}\n"
"\n"
"QPushButton#backButton:pressed{\n"
"    color: rgb(59, 59, 88);\n"
"}")
        self.backButton.setObjectName("backButton")
        self.addFilmButton = QtWidgets.QPushButton(self.frame)
        self.addFilmButton.setGeometry(QtCore.QRect(1100, 80, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(25)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.addFilmButton.setFont(font)
        self.addFilmButton.setStyleSheet("QPushButton#addFilmButton{\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:1, x2:1, y2:0.307, stop:0.0909091 rgba(244, 108, 203, 255), stop:1 rgba(247, 127, 127, 255));\n"
"border-radius:15px;\n"
"font: 25pt \"Segoe UI\";\n"
"color:rgb(200, 200, 200);\n"
"\n"
"}\n"
"QPushButton#addFilmButton:hover {\n"
"    font:  75 22pt \"Segoe UI\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#addFilmButton:pressed{\n"
"    \n"
"    color: rgb(59, 59, 88);\n"
"}")
        self.addFilmButton.setObjectName("addFilmButton")
        self.resetFilmButton = QtWidgets.QPushButton(self.frame)
        self.resetFilmButton.setGeometry(QtCore.QRect(240, 80, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(23)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.resetFilmButton.setFont(font)
        self.resetFilmButton.setStyleSheet("QPushButton#resetFilmButton{\n"
"color: qlineargradient(spread:pad, x1:0, y1:0.460227, x2:1, y2:0.46, stop:0 rgba(231, 126, 186, 255), stop:1 rgba(170, 85, 255, 255));\n"
"font: 23pt \"Segoe UI\";\n"
"\n"
"}\n"
"QPushButton#resetFilmButton:hover {\n"
"    font:  75 18pt \"Segoe UI\";\n"
"}\n"
"\n"
"QPushButton#resetFilmButton:pressed{\n"
"    color: rgb(59, 59, 88);\n"
"}")
        self.resetFilmButton.setObjectName("resetFilmButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Film-Management"))
        self.checkBox.setText(_translate("Form", "     Serie"))
        self.label_2.setText(_translate("Form", "Filter"))
        self.checkBox_2.setText(_translate("Form", "     Film"))
        self.checkBox_3.setText(_translate("Form", "      Serie"))
        self.label_3.setText(_translate("Form", "Filter"))
        self.checkBox_4.setText(_translate("Form", "      Film"))
        self.exit.setText(_translate("Form", "X"))
        self.backButton.setText(_translate("Form", "<"))
        self.addFilmButton.setText(_translate("Form", "+"))
        self.resetFilmButton.setText(_translate("Form", "<"))
