# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'filmManager.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1013, 432)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1011, 431))
        self.frame.setStyleSheet("background-color: rgb(59, 59, 88);\n"
"border-radius:10px;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(60, 25, 351, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(27)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0.460227, x2:1, y2:0.46, stop:0 rgba(231, 126, 186, 255), stop:1 rgba(170, 85, 255, 255));")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.exit = QtWidgets.QPushButton(self.frame)
        self.exit.setGeometry(QtCore.QRect(980, 5, 22, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.exit.setFont(font)
        self.exit.setStyleSheet("QPushButton#exit{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.460227, x2:1, y2:0.46, stop:0 rgba(231, 126, 186, 255), stop:1 rgba(170, 85, 255, 255));\n"
"border-radius:10px;\n"
"font: 10pt \"Segoe UI\";\n"
"color:rgb(200, 200, 200);\n"
"}\n"
"QPushButton#exit:hover {\n"
"    font:  75 12pt \"Segoe UI\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#exit:pressed{\n"
"    \n"
"    color: rgb(59, 59, 88);\n"
"}")
        self.exit.setObjectName("exit")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(95, 120, 891, 281))
        self.frame_3.setStyleSheet("background-color: rgb(39, 39, 60);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.videoList = QtWidgets.QListWidget(self.frame_3)
        self.videoList.setGeometry(QtCore.QRect(15, 10, 861, 261))
        self.videoList.setStyleSheet("font: 20pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);")
        self.videoList.setObjectName("videoList")
        self.backButton = QtWidgets.QPushButton(self.frame)
        self.backButton.setGeometry(QtCore.QRect(20, 30, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.backButton.setFont(font)
        self.backButton.setStyleSheet("QPushButton#backButton{\n"
"color: qlineargradient(spread:pad, x1:0, y1:0.460227, x2:1, y2:0.46, stop:0 rgba(231, 126, 186, 255), stop:1 rgba(170, 85, 255, 255));\n"
"font: 30pt \"Segoe UI\";\n"
"\n"
"}\n"
"QPushButton#backButton:hover {\n"
"    font:  75 25pt \"Segoe UI\";\n"
"}\n"
"\n"
"QPushButton#backButton:pressed{\n"
"    color: rgb(59, 59, 88);\n"
"}")
        self.backButton.setObjectName("backButton")
        self.addFilmButton = QtWidgets.QPushButton(self.frame)
        self.addFilmButton.setGeometry(QtCore.QRect(955, 80, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(25)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.addFilmButton.setFont(font)
        self.addFilmButton.setStyleSheet("QPushButton#addFilmButton{\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:1, x2:1, y2:0.307, stop:0.0909091 rgba(244, 108, 203, 255), stop:1 rgba(247, 127, 127, 255));\n"
"border-radius:15px;\n"
"font: 25pt \"Segoe UI\";\n"
"color:rgb(200, 200, 200);\n"
"\n"
"}\n"
"QPushButton#addFilmButton:hover {\n"
"    font:  75 22pt \"Segoe UI\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#addFilmButton:pressed{\n"
"    \n"
"    color: rgb(59, 59, 88);\n"
"}")
        self.addFilmButton.setObjectName("addFilmButton")
        self.resetFilmButton = QtWidgets.QPushButton(self.frame)
        self.resetFilmButton.setGeometry(QtCore.QRect(95, 80, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(23)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.resetFilmButton.setFont(font)
        self.resetFilmButton.setStyleSheet("QPushButton#resetFilmButton{\n"
"color: qlineargradient(spread:pad, x1:0, y1:0.460227, x2:1, y2:0.46, stop:0 rgba(231, 126, 186, 255), stop:1 rgba(170, 85, 255, 255));\n"
"font: 23pt \"Segoe UI\";\n"
"\n"
"}\n"
"QPushButton#resetFilmButton:hover {\n"
"    font:  75 18pt \"Segoe UI\";\n"
"}\n"
"\n"
"QPushButton#resetFilmButton:pressed{\n"
"    color: rgb(59, 59, 88);\n"
"}")
        self.resetFilmButton.setObjectName("resetFilmButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Film-Management"))
        self.exit.setText(_translate("Form", "X"))
        self.backButton.setText(_translate("Form", "<"))
        self.addFilmButton.setText(_translate("Form", "+"))
        self.resetFilmButton.setText(_translate("Form", "<"))
