# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manager.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Manager(object):
    def setupUi(self, Manager):
        Manager.setObjectName("Manager")
        Manager.resize(1166, 326)
        self.frame = QtWidgets.QFrame(Manager)
        self.frame.setGeometry(QtCore.QRect(10, 0, 1151, 321))
        self.frame.setStyleSheet("background-color: rgb(59, 59, 88);\n"
"border-radius:10px;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.helloMsg = QtWidgets.QLabel(self.frame)
        self.helloMsg.setGeometry(QtCore.QRect(30, 30, 1031, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.helloMsg.setFont(font)
        self.helloMsg.setStyleSheet("color:qlineargradient(spread:reflect, x1:0, y1:1, x2:1, y2:0.307, stop:0.0909091 rgba(244, 108, 203, 255), stop:1 rgba(247, 127, 127, 255));\n"
"font: 26pt \"Segoe UI\";")
        self.helloMsg.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.helloMsg.setObjectName("helloMsg")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(30, 140, 251, 151))
        self.frame_2.setStyleSheet("background-color: rgb(39, 39, 60);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 241, 131))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(119, 119, 130);\n"
"font: 14pt \"Segoe UI\";\n"
"")
        self.label_2.setObjectName("label_2")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(300, 140, 261, 151))
        self.frame_3.setStyleSheet("background-color: rgb(39, 39, 60);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 211, 121))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(119, 119, 130);\n"
"font: 14pt \"Segoe UI\";\n"
"")
        self.label_3.setObjectName("label_3")
        self.exit = QtWidgets.QPushButton(self.frame)
        self.exit.setGeometry(QtCore.QRect(1120, 10, 22, 22))
        self.exit.setStyleSheet("QPushButton#exit{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.460227, x2:1, y2:0.46, stop:0 rgba(231, 126, 186, 255), stop:1 rgba(170, 85, 255, 255));\n"
"border-radius:10px;\n"
"font: 10pt \"Segoe UI\";\n"
"color:rgb(200, 200, 200);\n"
"}\n"
"QPushButton#exit:hover {\n"
"    font:  75 12pt \"Segoe UI\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#exit:pressed{\n"
"    \n"
"    color: rgb(59, 59, 88);\n"
"}")
        self.exit.setObjectName("exit")
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setGeometry(QtCore.QRect(580, 140, 261, 151))
        self.frame_5.setStyleSheet("background-color: rgb(39, 39, 60);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_5 = QtWidgets.QLabel(self.frame_5)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 211, 121))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("font: 14pt \"Segoe UI\";\n"
" color: rgb(119, 119, 130);")
        self.label_5.setObjectName("label_5")
        self.frame_10 = QtWidgets.QFrame(self.frame)
        self.frame_10.setGeometry(QtCore.QRect(860, 140, 261, 151))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.frame_10.setFont(font)
        self.frame_10.setStyleSheet("background-color: rgb(39, 39, 60);")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.label_6 = QtWidgets.QLabel(self.frame_10)
        self.label_6.setGeometry(QtCore.QRect(10, 20, 231, 121))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(119, 119, 130);\n"
"font: 14pt \"Segoe UI\";\n"
"")
        self.label_6.setObjectName("label_6")
        self.filmManagementButton = QtWidgets.QPushButton(self.frame)
        self.filmManagementButton.setGeometry(QtCore.QRect(30, 100, 201, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.filmManagementButton.setFont(font)
        self.filmManagementButton.setStyleSheet("QPushButton#filmManagementButton{\n"
"    background-color:  qlineargradient(spread:reflect, x1:0, y1:1, x2:1, y2:0.307, stop:0.0909091 rgba(244, 108, 203, 255), stop:1 rgba(247, 127, 127, 255));\n"
"    QFrame::Shadow:100px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton#filmManagementButton:hover {\n"
"    font:  100 18pt \"Segoe UI\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#filmManagementButton:pressed{\n"
"    \n"
"    color: rgb(59, 59, 88);\n"
"}")
        self.filmManagementButton.setObjectName("filmManagementButton")
        self.CrewManagementButton = QtWidgets.QPushButton(self.frame)
        self.CrewManagementButton.setGeometry(QtCore.QRect(300, 100, 201, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.CrewManagementButton.setFont(font)
        self.CrewManagementButton.setStyleSheet("QPushButton#CrewManagementButton{\n"
"    background-color:  qlineargradient(spread:reflect, x1:0, y1:1, x2:1, y2:0.307, stop:0.0909091 rgba(244, 108, 203, 255), stop:1 rgba(247, 127, 127, 255));\n"
"    QFrame::Shadow:100px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton#CrewManagementButton:hover {\n"
"    font:  75 18pt \"Segoe UI\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#CrewManagementButton:pressed{\n"
"    \n"
"    color: rgb(59, 59, 88);\n"
"}")
        self.CrewManagementButton.setObjectName("CrewManagementButton")
        self.bewertungButton = QtWidgets.QPushButton(self.frame)
        self.bewertungButton.setGeometry(QtCore.QRect(580, 100, 201, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.bewertungButton.setFont(font)
        self.bewertungButton.setStyleSheet("QPushButton#bewertungButton{\n"
"    background-color:  qlineargradient(spread:reflect, x1:0, y1:1, x2:1, y2:0.307, stop:0.0909091 rgba(244, 108, 203, 255), stop:1 rgba(247, 127, 127, 255));\n"
"    QFrame::Shadow:100px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton#bewertungButton:hover {\n"
"    font:  75 20pt \"Segoe UI\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#bewertungButton:pressed{\n"
"    \n"
"    color: rgb(59, 59, 88);\n"
"}")
        self.bewertungButton.setObjectName("bewertungButton")
        self.vorschlaegeButton = QtWidgets.QPushButton(self.frame)
        self.vorschlaegeButton.setGeometry(QtCore.QRect(860, 100, 201, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.vorschlaegeButton.setFont(font)
        self.vorschlaegeButton.setStyleSheet("QPushButton#vorschlaegeButton{\n"
"    background-color:  qlineargradient(spread:reflect, x1:0, y1:1, x2:1, y2:0.307, stop:0.0909091 rgba(244, 108, 203, 255), stop:1 rgba(247, 127, 127, 255));\n"
"    QFrame::Shadow:100px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton#vorschlaegeButton:hover {\n"
"    font:  75 20pt \"Segoe UI\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#vorschlaegeButton:pressed{\n"
"    \n"
"    color: rgb(59, 59, 88);\n"
"}\n"
"")
        self.vorschlaegeButton.setObjectName("vorschlaegeButton")
        self.editButton = QtWidgets.QPushButton(self.frame)
        self.editButton.setGeometry(QtCore.QRect(1060, 40, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.editButton.setFont(font)
        self.editButton.setStyleSheet("QPushButton#editButton{\n"
"color:qlineargradient(spread:reflect, x1:0, y1:1, x2:1, y2:0.307, stop:0.0909091 rgba(244, 108, 203, 255), stop:1 rgba(247, 127, 127, 255));\n"
"font: 22pt \"Segoe UI\";\n"
"}\n"
"QPushButton#editButton:hover {\n"
"    font:  75 25pt \"Segoe UI\";\n"
"}\n"
"\n"
"QPushButton#editButton:pressed{\n"
"    \n"
"    color: rgb(59, 59, 88);\n"
"}")
        self.editButton.setObjectName("editButton")
        self.frame_3.raise_()
        self.helloMsg.raise_()
        self.frame_2.raise_()
        self.exit.raise_()
        self.frame_5.raise_()
        self.frame_10.raise_()
        self.filmManagementButton.raise_()
        self.CrewManagementButton.raise_()
        self.bewertungButton.raise_()
        self.vorschlaegeButton.raise_()
        self.editButton.raise_()

        self.retranslateUi(Manager)
        QtCore.QMetaObject.connectSlotsByName(Manager)

    def retranslateUi(self, Manager):
        _translate = QtCore.QCoreApplication.translate
        Manager.setWindowTitle(_translate("Manager", "Form"))
        self.helloMsg.setText(_translate("Manager", "<WELCOME_NOTIFY>"))
        self.label_2.setText(_translate("Manager", "<html><head/><body><p>Filme hinzufügen / löschen</p><p>Serien hinzufügen / löschen</p></body></html>"))
        self.label_3.setText(_translate("Manager", "<html><head/><body><p>Personen hinzufügen</p><p>Personen löschen</p></body></html>"))
        self.exit.setText(_translate("Manager", "X"))
        self.label_5.setText(_translate("Manager", "<html><head/><body><p>Filme bewerten</p><p>Bewertungen ansehen</p></body></html>"))
        self.label_6.setText(_translate("Manager", "<html><head/><body><p>Filme und Serien die dir </p><p>vorgeschlagen werden</p></body></html>"))
        self.filmManagementButton.setText(_translate("Manager", "Film-Management"))
        self.CrewManagementButton.setText(_translate("Manager", "Crew-Management"))
        self.bewertungButton.setText(_translate("Manager", "Bewertung"))
        self.vorschlaegeButton.setText(_translate("Manager", "Vorschläge"))
        self.editButton.setText(_translate("Manager", "⌥"))
